### PR TITLE
add mlir-trunk

### PR DESCRIPTION
**Pull request by Sameeranjoshi**

### CODE REVIEW

**Comment by partouf** [comment]
Hi, Sorry I wasn't clear.

You should be using the `image` `clang`, which refers to this repo https://github.com/compiler-explorer/clang-builder

And then run `make build-yamls` again

**Comment by Sameeranjoshi** [comment]
Please check

**Comment by Sameeranjoshi** [comment]
Missed the build command

**Comment by Sameeranjoshi** [comment]
Sending a new patch again sorry, I was editing in browser.

**Comment by Sameeranjoshi** [comment]
Ok sent a new updated patch.

**Comment by partouf** [comment]
Thanks

I started a build https://github.com/compiler-explorer/compiler-workflows/actions/runs/5147508932/jobs/9267984210

**Comment by Sameeranjoshi** [comment]
ok now that this is built successfully can you please point what are the next steps to integrate this and have a trunk in CE ?

**Pull request merged**
