### PR TITLE
Add p3367 (constexpr coroutines)

### PR DESCRIPTION
**Pull request by hanickadot**

### CODE REVIEW

**Comment by mattgodbolt** [comment]
This is missing the step that updates the workflows.

In order to make these PRs you need to only update the YAML then `make build-yamls` (which is automatically done if you enable precommit hooks) - this will update the other files automatically :)

**Comment by mattgodbolt** [comment]
building: https://github.com/compiler-explorer/compiler-workflows/actions/runs/10153614266

**Comment by partouf** [comment]
alas:
https://github.com/compiler-explorer/compiler-workflows/actions/runs/10153614266/job/28077266806#step:5:6464

```
  /root/llvm-project/clang/lib/AST/ExprConstant.cpp: In function '{anonymous}::EvalStmtResult EvaluateStmt({anonymous}::StmtResult&, {anonymous}::EvalInfo&, const clang::Stmt*, const clang::SwitchCase*)':
  /root/llvm-project/clang/lib/AST/ExprConstant.cpp:5415:12: error: 'r3' was not declared in this scope
   5415 |     return r3;
        |            ^~
  /root/llvm-project/clang/lib/AST/ExprConstant.cpp:5415:14: warning: this statement may fall through [-Wimplicit-fallthrough=]
   5415 |     return r3;
```

**Comment by hanickadot** [comment]
Damn! Silly me :(

**Comment by hanickadot** [comment]
It should be fixed.

**Pull request merged**
