### PR TITLE
 Add contracts-nonattr

### PR DESCRIPTION
**Pull request by villevoutilainen**
This adds a prototype implementation of https://open-std.org/JTC1/SC22/WG21/docs/papers/2023/p2961r0.pdf

### CODE REVIEW

**Comment by villevoutilainen** [comment]
@partouf @mattgodbolt can you assist with this? Looks like this one needs new yaml files. I can try doing that myself, but I'll be busy next week, and likely busy over the weekend too. If the current version stays up and running, daily builds are not so important, although it's nice to have them if I start fixing testers' findings already next week. :)

**Comment by partouf** [comment]
yes we need to run a make script on a linux machine, but i am currently too lazy to reboot right now, will do in a few hours probably

**Comment by villevoutilainen** [comment]
At any rate, if you can, please rebuild the compiler, it has some rather important bug fixes added since the initial go-live. :)

**Comment by mattgodbolt** [comment]
I'm on this now

**Pull request merged**
